#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 24 18:12:34 2020

@author: rustybilges
"""

MAPPING = {'GCS': {'interventionIds' : [1830], 
                         'attributeIds' : [6844], 
                         'column' : ['valueNumber'],
                         'table' : ['PtAssessment']},
            'FiO2': {'interventionIds' : [4790, 3231, 4322], 
                         'attributeIds' : [25649, 19522, 16240], 
                         'column' : ['valueNumber', 'valueNumber', 'valueString'],
                         'table' : ['PtLabResult', 'PtAssessment', 'PtLabResult']},
            'PEEP': {'interventionIds' : [3036], 
                     'attributeIds' : [4620], 
                     'column' : ['valueNumber'],
                     'table' : ['PtAssessment']}, 
             'Bilirubin': {'interventionIds' : [4651], 
                     'attributeIds' : [25545], 
                     'column' : ['valueNumber'],
                     'table' : ['PtLabResult']},
             'Platelets': {'interventionIds' : [522, 22544, 9502], 
                     'attributeIds' : [7153, 43949, 16240], 
                     'column' : ['valueNumber', 'valueNumber', 'valueString'],
                     'table' : ['PtLabResult', 'PtLabResult','PtLabResult']},
             'Creatinine': {'interventionIds' : [758], 
                     'attributeIds' : [12200], 
                     'column' : ['valueNumber'],
                     'table' : ['PtLabResult']},
                               
             'MAP': {'interventionIds' : [3469, 7833, 7833, 21038, 22287, 22287,
                                          3363, 7794, 7794, 21039, 21039], 
                     'attributeIds' : [71, 27352, 27356, 43409, 43797, 43801,
                                       10660, 27260, 27264, 43381, 43388], 
                     'column' : ['valueNumber', 'valueNumber', 'valueNumber', 
                                 'valueNumber', 'valueNumber', 'valueNumber', 
                                 'valueNumber', 'valueNumber', 'valueNumber', 
                                 'valueNumber', 'valueNumber'],
                     'table' : ['PtAssessment', 'PtAssessment','PtAssessment',
                                'PtAssessment', 'PtAssessment', 'PtAssessment',
                                'PtAssessment', 'PtAssessment', 'PtAssessment',
                                'PtAssessment', 'PtAssessment']},
            'PO2': {'interventionIds' : [734, 13963, 48950, 48968], 
                     'attributeIds' : [10592, 37502, 16240, 16240], 
                         'column' : ['valueNumber', 'valueNumber', 
                                     'valueString', 'valueString'],
                     'table' : ['PtLabResult','PtLabResult',
                                'PtLabResult','PtLabResult']},
                     
             'Adrenaline': {'interventionIds' : [5090], 
                     'attributeIds' : [52150], 
                     'column' : ['valueNumber'], 
                     'table' : ['PtMedication']},
             'Noradrenaline': {'interventionIds' : [4626], 
                     'attributeIds' : [52150], 
                     'column' : ['valueNumber'], 
                     'table' : ['PtMedication']},                                
             'Dobutamine': {'interventionIds' : [5100], 
                     'attributeIds' : [52150], 
                     'column' : ['valueNumber'], 
                     'table' : ['PtMedication']},           
             'Dopamine': {'interventionIds' : [5137], 
                     'attributeIds' : [52150], 
                     'column' : ['valueNumber'], 
                     'table' : ['PtMedication']},                                
             }

DUMMY_MAPPING = {'GCS': {'interventionIds' : [10], 
                         'attributeIds' : [2], 
                         'column' : [0.8]},
                 'MAP': {'interventionIds' : [70, 60, 80], 
                         'attributeIds' : [5, 3, 9], 
                         'column' : [0.5, 0.4, 0.6]},
                 'Adrenaline': {'interventionIds' : [0.1, 0.05], 
                         'attributeIds' : [0.1, 0.3], 
                         'column' : [0.5, 0.4]},
                 'Noradrenaline': {'interventionIds' : [0.1, 0.05], 
                         'attributeIds' : [0.1, 0.3], 
                         'column' : [0.5, 0.4]},                                
                 'Dobutamine': {'interventionIds' : [0.1], 
                         'attributeIds' : [0.1], 
                         'column' : [0.5]},           
                 'Dopamine': {'interventionIds' : [0.1, 0.05], 
                         'attributeIds' : [0.1, 0.3], 
                         'column' : [0.5, 0.4]},                                
                 'Bilirubin': {'interventionIds' : [6.1], 
                         'attributeIds' : [2.1], 
                         'column' : [0.1]},
                 'Platelets': {'interventionIds' : [60], 
                         'attributeIds' : [10.0], 
                         'column' : [0.1]},
                 'Creatinine': {'interventionIds' : [2.0], 
                         'attributeIds' : [1.0], 
                         'column' : [0.2]},
                 'PEEP': {'interventionIds' : [5.0], 
                         'attributeIds' : [1.0], 
                         'column' : [0.8]},                                
                 'FiO2': {'interventionIds' : [5.0], 
                         'attributeIds' : [1.0], 
                         'column' : [0.8]},
                 'PO2': {'interventionIds' : [5.0], 
                         'attributeIds' : [1.0], 
                         'column' : [0.8]}}